export const COUNTRIES = [
  'Netherlands',
  'Belgium',
  'Germany',
  'France',
  'United Kingdom',
  'United States',
  'Canada',
  'Spain',
  'Italy',
  'Portugal',
  'Poland',
  'Romania',
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Austria',
  'Switzerland',
  'Ireland',
  'South Africa',
  'Nigeria',
  'Kenya',
  'Ghana',
  'Indonesia',
  'India',
  'Philippines',
  'Brazil',
  'Mexico',
  'Argentina',
  'Colombia',
  'Australia',
  'New Zealand',
  'Japan',
  'South Korea',
  'China',
  'Singapore',
  'Malaysia',
  'Thailand',
  'Vietnam',
  'Russia',
  'Ukraine',
  'Turkey',
  'Egypt',
  'Morocco',
  'Israel',
  'United Arab Emirates',
  'Saudi Arabia',
  'Other',
] as const;

export type Country = (typeof COUNTRIES)[number];
